### ISSUE TITLE
Category Hiding not working

### ISSUE THREAD

**Issue by Saereth** [CraftTweaker/JEITweaker#18]
mc 1.16.5
CraftTweaker-1.16.5-7.1.0.355.jar
JEITweaker-1.16.5-1.0.1.33.jar
jei-1.16.5-7.7.1.110.jar

jei.zs:
`import mods.jei.JEI;
	mods.jei.JEI.hideCategory("appliedenergistics2.inscriber");
`
this throws the error ingame
![image](https://user-images.githubusercontent.com/9200909/126186099-9f4d9ae8-935b-4e08-aaf9-8378c2b0a793.png)

Not sure why its prepending minecraft: onto the category, the category I go from the output of /ct dump jeiCategories

**Comment by jaredlll08** [comment]
So I just checked in-game.

This is the output of `/ct dump jeiCategories`
```
List of all known JEI categories: 
- minecraft:crafting
- minecraft:anvil
- minecraft:blasting
- minecraft:brewing
- minecraft:campfire
- minecraft:fuel
- minecraft:furnace
- minecraft:smithing
- minecraft:smoking
- minecraft:stonecutting
- appliedenergistics2:appliedenergistics2.inscriber
- appliedenergistics2:condenser
- appliedenergistics2:grinder
- jei:information
```
and using:
```zenscript
mods.jei.JEI.hideCategory("appliedenergistics2:appliedenergistics2.inscriber");
```

Appears to work.

The reason that it was adding `minecraft:` to the start was because it is a ResourceLocation, meaning it needs to be `modid:path`, but when we make it, if there is no modid (no `:`), it gets defaulted to `minecraft`.

Please let me know if you run into any other issues :)
